### PR TITLE
ISLANDORA-1826 Remove ambiguous wording from batch queue / set pages

### PR DESCRIPTION
**Pull request by joshdentremont**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1826
# What does this Pull Request do?

Updates wording so 'delete set' becomes 'delete set from queue' and 'delete item' becomes 'delete item from queue'
# What's new?

Just updated wording.
# How should this be tested?

Visit batch queue and batch set pages to see the new wording.
# Additional Notes:
# Interested parties

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@J77D will check tomorrow. Thanks

**Comment by whikloj** [comment]
I'm good with this, but I'm dragging @rosiel and @willtp87 in because they have been good at reviewing user-centric wording. My words not good always.

**Comment by DiegoPino** [comment]
I'm also ok with this, just not sure if a SET belongs really to the "queue" (i mean i'm not sure if  "queue" is the correct term here, being a "SET" nothing else than a grouping value and what really belongs to the queue is each individual batch object(preprocess object). Maybe i'm being too picky! 😄  Any third pair of eyes on this are welcome  ( @whikloj == second pair) and i agree on whatever others think of.

**Comment by willtp87** [comment]
Hi folks,

I think you are on the right track @DiegoPino and I think the right place to disambiguate this is in the deletion confirm screen where we can be a bit more verbose. We can add an explicit note there to re-enforce that existing objects won't be purged.

Thanks!

**Comment by whikloj** [comment]
@J77D would you like to add @willtp87's suggestion to your PR? 

A simple note on the deletion confirmation screen that you are deleting the item from the batch queue and **not** deleting the actual item from your repository.

**Comment by joshdentremont** [comment]
@willtp87 @whikloj I replaced the "This action cannot be undone" message on the set delete and item delete confirmation pages with:

This will delete the set from the batch queue. Ingested objects will not be deleted from your repository. 
and
This will delete the item from the batch queue. Ingested objects will not be deleted from your repository. 

Does that sound OK?

**Comment by willtp87** [comment]
For clarity I was suggesting that the ' from queue' additions in this pull be replaced by the changes to the confirmation screens.

**Comment by joshdentremont** [comment]
@willtp87 @whikloj @DiegoPino

I agree that the confirmation screens are the best place to fully explain what is going on, but I still think having the 'from queue' part is better than not having it. That being said, maybe there is a third option that would be better yet, or maybe I'm overthinking it. :)

The issue I have with the original wording is that if someone were to think that the delete button was for removing the objects from the repository they could end up with a large batch queue which I believe can fill up /sites/default/files with unnecessary metadata, PDFs, images, etc. 

I'm certainly no expert on wording so I will support whatever decision you make on this. I will create a JIRA ticket for the documentation to add a bit about how items in the queue can fill your hard drive so hopefully that will help with the problem I describe above.

If you do want to go with just the second commit, are you able to cherry-pick it or should I push a third commit that undoes the first one?

Thanks for your input.

**Comment by willtp87** [comment]
@J77D 
I think your third option could be writing an entry in the troubleshooting section of the README about the disk usage.  As @DiegoPino  pointed out there are issues with the ' from queue' additions. I think it would be easiest and clearest if the current pull were updated by the third commit you mention.

**Comment by joshdentremont** [comment]
@willtp87 3rd commit has been pushed.

**Review by DonRichards — COMMENTED** [review]
This looks good and the wording makes sense

**Review by DonRichards — APPROVED** [review]
Sorry, I meant to click approve with my comment.

**Pull request merged**
