### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by mrmiguez**
Added screenshot and details to Configuration in README

### CODE REVIEW

**Comment by whikloj** [comment]
@mrmiguez thanks for the PR, can I ask you to fill out an Individual Contributor License Agreement (iCLA) available [here](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements)

**Comment by manez** [comment]
@whikloj @mrmiguez iCLA now on file! Thanks!

**Comment by whikloj** [comment]
Thank you @manez 

@mrmiguez I'm wondering if you could upload your image to github and update your PR to reference it there. You can simply download the image and drop it into a comment (even right here). Then you can copy the Image URL and use that. Keeps Github and Confluence separate.

**Comment by mrmiguez** [comment]
image2016-9-28 10-51-43

**Comment by mrmiguez** [comment]
@whikloj Done!

**Review by whikloj — APPROVED** [review]
Looks good, thanks for this!

**Pull request merged**
