### PR TITLE
Avoid method name collision with islandora_importer.

### PR DESCRIPTION
**Pull request by whikloj**
Addresses [ISLANDORA-1429](https://jira.duraspace.org/browse/ISLANDORA-1429)

### CODE REVIEW

**Comment by willtp87** [comment]
Looks like I [commented](https://github.com/Islandora/islandora_batch/pull/65#issuecomment-138606443) on the wrong pull and missed a [comment](https://github.com/Islandora/islandora_batch/pull/57#issuecomment-137835377)

**Comment by whikloj** [comment]
Ok, so I think I missed something from @adam-vessey's original comments. 

Would the point of removing the type hinting be to allow islandora_importer to override the getNamespace method cleanly?

I wasn't exactly clear why this was happening, but if that is what I was missing then I agree with @willtp87 and @adam-vessey that removing the type hint is the better path and I will update the PR. Just looking for a :+1: confirmation.

And @ruebot, yes this is to cover the changes based on the PR comments.

**Comment by willtp87** [comment]
Can we change the name to something more generic? sub-classes may re-implement the method and the name (specifically getting it from the parent) may become nonsensical. How about `determineNamespace` ?

**Comment by whikloj** [comment]
Ok, but if we are going to continue with a change to the name. Do I need to remove the type hint?

**Comment by willtp87** [comment]
Yeah that's what Adam was getting at.  This is a very strange problem, it depends deeply on what people would be less surprised by. I'm divided, but think now that the name change is the way to go. (type hint would not need to change)

**Comment by whikloj** [comment]
Ok, I'll proceed with changing the method name here to `determineNamespace`, leave the type hint in place for this method. 

That will resolve the immediate issues and if in future we want to bring the two methods into one, so be it.

**Pull request merged**
