### PR TITLE
Added detailed example, courtesy of @ruebot.

### PR DESCRIPTION
**Pull request by mjordan**

### CODE REVIEW

**Comment by willtp87** [comment]
Should probably be in the examples for the Drush command.  Here is an example: https://github.com/drush-ops/drush/blob/52450fb721b1b405b7f551d595622006cf0d1f54/examples/sandwich.drush.inc#L46

**Comment by mjordan** [comment]
Sorry about the deletion, @ruebot please go ahead.

**Comment by mjordan** [comment]
@willtp87's call

**Comment by willtp87** [comment]
From what I gather we can close this and move forward on pull #26, if I'm wrong someone can just re-open.

**Pull request closed without merging**
